name: Runningisaskill.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38819
title: RUNNING IS A SKILL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#331308'
    - '#feffff'
    - '#f1301e'
    - '#e8b983'
    - '#47545d'
  brandStrength: 0.4336918
  lightness: 0
  saturation: 0.7222222
  rhythmicContrast: 0.75
purpose: []
