name: CALL 07843 501 006
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38819
title: CALL 07843 501 006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050503'
    - '#cecccd'
    - '#624607'
    - '#9f6b46'
    - '#be1721'
  brandStrength: 0.4336918
  lightness: 0
  saturation: 0.7222222
  rhythmicContrast: 0.75
purpose: []
