name: Runningisaskill.com
favicon: null
layout_spectrum: 0.69406
typography_spectrum: 0.38819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#304d6d'
    - '#ffffff'
    - '#a5b2bb'
    - '#967c61'
  brandStrength: 0.4336918
  lightness: 0
  saturation: 0.7222222
  rhythmicContrast: 0.75
purpose: []
