layout_spectrum: 0.5842294
color:
  saturation: 0.7222222
  lightness: 0
  brandStrength: 0.4336918
  brandColors:
    - '#FFFFFF'
    - '#020202'
    - '#454545'
    - '#B4A097'
    - '#FD7C39'
  rhythmicContrast: 0.7544803
typography_spectrum: 0.2956989
name: Runningisaskill.com
