name: RUNNING IS A SKILL
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38819
title: CALL 07843 501 006
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#CFE882'
    - '#9E2F3E'
    - '#C5EAFD'
    - '#A966AB'
    - '#B24C64'
  brandStrength: 1
  lightness: 0
  saturation: 0.7222222
  rhythmicContrast: 0.75
purpose: []
